In [20]:
import  torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

# 关于word embedding 以序列建模为例
# 考虑source sentence 和 target sentence
# 构建序列，序列的字符以索引的形式表示
batch_size =2
#单词表大小 
max_num_src_words = 8
max_num_trg_words = 8

#特征大小
model_dim = 8

#序列的最大长度
max_src_seq_len = 5
max_trg_seq_len = 5
max_position_len = 5

#src_len = torch.randint(2, 5, (batch_size,))
#trg_len = torch.randint(2, 5, (batch_size,))
src_len = torch.Tensor([2, 4]).to(torch.int32)
tgt_len = torch.Tensor([4, 3]).to(torch.int32)
print(src_len)
#单词索引构成的源句子和目标句子，并且做了padding，默认为0
src_seq = torch.cat([torch.unsqueeze(F.pad(torch.randint(1, max_num_src_words, (L,)),(0,max_src_seq_len-L)),0) for L in src_len] )

tgt_seq = torch.cat([torch.unsqueeze(F.pad(torch.randint(1, max_num_trg_words, (L,)),(0,max_trg_seq_len-L)),0) for L in tgt_len] )

#构建embedding 
src_embedding_table = nn.Embedding(max_num_src_words+1, model_dim)
trg_embedding_table = nn.Embedding(max_num_trg_words+1, model_dim)

src_embedding = src_embedding_table(src_seq)
tgt_embedding = trg_embedding_table(tgt_seq)

#构造position embedding 
pos_Mat = torch.arange(max_position_len).reshape((-1,1))
i_mat =torch.pow(10000,torch.arange(0,8,2).reshape((1,-1))/model_dim) 
pe_embedding_table = torch.zeros(max_position_len,model_dim)
pe_embedding_table[:,0::2] = torch.sin(pos_Mat/i_mat)
pe_embedding_table[:,1::2] = torch.cos(pos_Mat/i_mat)
print(pos_Mat)
print(pe_embedding_table)


# 
# print(src_embedding_table.weight)
# print(src_seq)
# print(src_embedding)


tensor([2, 4], dtype=torch.int32)
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  9.9833e-02,  9.9500e-01,  9.9998e-03,
          9.9995e-01,  1.0000e-03,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  1.9867e-01,  9.8007e-01,  1.9999e-02,
          9.9980e-01,  2.0000e-03,  1.0000e+00],
        [ 1.4112e-01, -9.8999e-01,  2.9552e-01,  9.5534e-01,  2.9995e-02,
          9.9955e-01,  3.0000e-03,  1.0000e+00],
        [-7.5680e-01, -6.5364e-01,  3.8942e-01,  9.2106e-01,  3.9989e-02,
          9.9920e-01,  4.0000e-03,  9.9999e-01]])


In [19]:
import torch

# 设置参数
max_position_len = 5  # 句子长度
embedding_dim = 7     # 嵌入向量维度

# 创建位置索引列向量
pos_Mat = torch.arange(max_position_len).unsqueeze(1)  # [seq_len, 1]

# 创建嵌入向量矩阵，这里我们随机生成一些值
embeddings = torch.randn(max_position_len, embedding_dim)  # [seq_len, embedding_dim]

# 创建位置编码矩阵
imat = torch.pow(10000, -torch.arange(0, embedding_dim, 2).div(embedding_dim))
peembeddingtable = torch.zeros(max_position_len, embedding_dim)
peembeddingtable[:, 0::2] = torch.sin(pos_Mat * imat)
peembeddingtable[:, 1::2] = torch.cos(pos_Mat * imat)

# 将位置编码添加到嵌入向量上
positional_embeddings = embeddings + peembeddingtable

# 打印结果
print("Position Indexes (as column vector):\n", pos_Mat)
print("\nEmbedding Vectors:\n", embeddings)
print("\nPositional Embedding Table:\n", peembeddingtable)
print("\nPositional Embeddings (Embeddings + Positional Embedding Table):\n", positional_embeddings)


RuntimeError: The expanded size of the tensor (3) must match the existing size (4) at non-singleton dimension 1.  Target sizes: [5, 3].  Tensor sizes: [5, 4]